const vehicles = [
  {id:1,make:'Toyota',model:'RAV4',year:2024,price:32990,miles:8200,type:'SUV',fuel:'Hybrid',condition:'New',img:'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=900&q=80',color:'Wind Chill Pearl'},
  {id:2,make:'Ford',model:'F-150 XLT',year:2023,price:41950,miles:15400,type:'Truck',fuel:'Gasoline',condition:'Used',img:'https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=900&q=80',color:'Carbonized Gray'},
  {id:3,make:'Honda',model:'Civic Sport',year:2024,price:27990,miles:3200,type:'Sedan',fuel:'Gasoline',condition:'New',img:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=80',color:'Platinum White'},
  {id:4,make:'Tesla',model:'Model 3 Long Range',year:2023,price:38900,miles:11100,type:'Sedan',fuel:'Electric',condition:'Used',img:'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=900&q=80',color:'Midnight Silver'},
  {id:5,make:'Jeep',model:'Wrangler Sahara',year:2022,price:36500,miles:24800,type:'SUV',fuel:'Gasoline',condition:'Used',img:'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=80',color:'Sarge Green'},
  {id:6,make:'BMW',model:'3 Series 330i',year:2023,price:44750,miles:9300,type:'Sedan',fuel:'Gasoline',condition:'Used',img:'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=900&q=80',color:'Alpine White'},
  {id:7,make:'Hyundai',model:'Ioniq 5 SEL',year:2024,price:45990,miles:4100,type:'Electric',fuel:'Electric',condition:'New',img:'https://images.unsplash.com/photo-1625047509248-ec889cbff17f?auto=format&fit=crop&w=900&q=80',color:'Digital Teal'},
  {id:8,make:'Chevrolet',model:'Tahoe LT',year:2021,price:42900,miles:35400,type:'SUV',fuel:'Gasoline',condition:'Used',img:'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=900&q=80',color:'Summit White'},
  {id:9,make:'Mercedes-Benz',model:'C 300',year:2024,price:51200,miles:1800,type:'Sedan',fuel:'Gasoline',condition:'New',img:'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=900&q=80',color:'Obsidian Black'},
  {id:10,make:'Audi',model:'Q5 Premium',year:2022,price:39800,miles:18900,type:'SUV',fuel:'Gasoline',condition:'Used',img:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=80',color:'Mythos Black'},
  {id:11,make:'Lexus',model:'RX 350',year:2023,price:47500,miles:7600,type:'SUV',fuel:'Hybrid',condition:'Used',img:'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=900&q=80',color:'Eminent White'},
  {id:12,make:'Range Rover',model:'Velar',year:2024,price:58900,miles:2500,type:'SUV',fuel:'Gasoline',condition:'New',img:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=80',color:'Santorini Black'}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>'$'+Number(n).toLocaleString();
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),3200)}
function card(v){const detail=location.pathname.includes('/pages/')?'vehicle-details.html':'pages/vehicle-details.html';return `<article class="card"><img loading="lazy" class="vehicle-img" src="${v.img}" alt="${v.year} ${v.make} ${v.model}"><div class="card-body"><span class="tag">${v.condition} · ${v.type}</span><h3>${v.year} ${v.make} ${v.model}</h3><div class="vehicle-meta"><span>${v.miles.toLocaleString()} mi</span><span>${v.fuel}</span><span>${v.color}</span></div><p class="price">${money(v.price)}</p><a class="btn" href="${detail}?id=${v.id}">View details</a></div></article>`}
function initNav(){const b=$('.menu-btn');if(b)b.onclick=()=>$('.nav-links').classList.toggle('open');const current=location.pathname.split('/').pop()||'index.html',prefix=location.pathname.includes('/pages/')?'':'pages/';const nav=$('.nav-links');if(nav&&!nav.querySelector('[data-condition]'))nav.insertAdjacentHTML('afterbegin',`<a data-condition href="${prefix}inventory.html?condition=New">New cars</a><a data-condition href="${prefix}inventory.html?condition=Used">Used cars</a>`);$$('.nav-links a').forEach(a=>{if(a.getAttribute('href')===current)a.classList.add('active')});if(!$('#floatingWhatsApp')){const w=document.createElement('a');w.id='floatingWhatsApp';w.className='whatsapp-float';w.href='https://wa.me/15550142024';w.target='_blank';w.rel='noopener';w.textContent='WhatsApp';document.body.append(w)}}
function initInventory(){const out=$('#inventoryGrid');if(!out)return;let page=1,mode='grid';const params=new URLSearchParams(location.search);const render=()=>{let q=($('#search')?.value||'').toLowerCase(),type=$('#type')?.value||'',condition=params.get('condition')||'';let arr=vehicles.filter(v=>(`${v.make} ${v.model}`.toLowerCase().includes(q)||String(v.year).includes(q))&&(!type||v.type===type)&&(!condition||v.condition===condition));const sort=$('#sort')?.value||'';if(sort==='price-asc')arr.sort((a,b)=>a.price-b.price);if(sort==='price-desc')arr.sort((a,b)=>b.price-a.price);if(sort==='miles')arr.sort((a,b)=>a.miles-b.miles);const pages=Math.max(1,Math.ceil(arr.length/6));page=Math.min(page,pages);out.className='grid grid-3 inventory-grid '+mode;out.innerHTML=arr.slice((page-1)*6,page*6).map(card).join('')||'<p>No vehicles match your search.</p>';if($('#pagination'))$('#pagination').innerHTML=Array.from({length:pages},(_,i)=>`<button class="${i+1===page?'active':''}" data-p="${i+1}">${i+1}</button>`).join('');$$('[data-p]').forEach(x=>x.onclick=()=>{page=+x.dataset.p;render()})};['search','type','sort'].forEach(id=>$('#'+id)?.addEventListener('input',()=>{page=1;render()}));$('#gridView')?.addEventListener('click',()=>{mode='grid';render()});$('#listView')?.addEventListener('click',()=>{mode='list';render()});render()}
function initDetails(){const el=$('#vehicleDetail');if(!el)return;const v=vehicles.find(x=>x.id===+(new URLSearchParams(location.search).get('id')||1))||vehicles[0];el.innerHTML=`<div class="gallery"><img class="gallery-main" src="${v.img}" alt="${v.make} ${v.model}"><img src="${v.img}" alt="${v.make} ${v.model} side view"><img src="${v.img}" alt="${v.make} ${v.model} rear view"></div><div><span class="tag">${v.condition} · ${v.type}</span><h1>${v.year} ${v.make} ${v.model}</h1><p class="price">${money(v.price)}</p><p class="muted">${v.miles.toLocaleString()} miles · ${v.fuel} · ${v.color}</p><ul class="checklist"><li>One-owner history</li><li>Multi-point inspected</li><li>Free CARFAX report</li><li>7-day exchange policy</li></ul><a class="btn" href="test-drive.html?id=${v.id}">Book a test drive</a> <a class="btn outline" target="_blank" rel="noopener" href="https://wa.me/15550142024?text=${encodeURIComponent(`Hello AutoZone, I am interested in the ${v.make} ${v.model} ${v.year} listed at ${money(v.price)}.`)}">WhatsApp inquiry</a></div>`}
function initForms(){ $$('form[data-toast]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const key=f.id==='testDriveForm'?'testDriveBookings':f.id==='contactForm'?'contactMessages':f.id==='serviceForm'?'serviceBookings':'newsletterSubscribers';const saved=JSON.parse(localStorage.getItem(key)||'[]');saved.push({...Object.fromEntries(new FormData(f)),createdAt:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(saved));toast(f.dataset.toast);f.reset()}));const test=$('#testDriveForm'),id=new URLSearchParams(location.search).get('id');if(test&&id){const select=test.querySelector('[name="vehicle"]');const v=vehicles.find(x=>x.id===+id);if(select&&v){select.innerHTML=vehicles.map(x=>`<option value="${x.id}" ${x.id===v.id?'selected':''}>${x.year} ${x.make} ${x.model}</option>`).join('')}}const calc=$('#financeCalc');if(calc)calc.addEventListener('submit',e=>{e.preventDefault();const p=+$('#amount').value||0,d=+$('#down').value||0,r=(+$('#rate').value||7.9)/1200,n=+$('#term').value||60,loan=p-d,m=r?loan*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):loan/n;$('#payment').textContent=money(m.toFixed(0))+'/mo'})}
function initAdmin(){const table=$('#adminVehicles');if(!table)return;const render=()=>{const custom=JSON.parse(localStorage.getItem('autozone_custom')||'[]');table.innerHTML=[...vehicles,...custom].map(v=>`<tr><td>${v.year} ${v.make} ${v.model}</td><td>${money(v.price)}</td><td>${v.type}</td><td><button class="btn danger" data-del="${v.id}">Delete</button></td></tr>`).join('');$$('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Remove this vehicle?')){const custom=JSON.parse(localStorage.getItem('autozone_custom')||'[]');localStorage.setItem('autozone_custom',JSON.stringify(custom.filter(v=>v.id!==+b.dataset.del)));toast('Vehicle removed');render()}})};render();$('#addVehicle')?.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),custom=JSON.parse(localStorage.getItem('autozone_custom')||'[]');custom.push({...d,id:Date.now(),year:+d.year,price:+d.price,miles:+d.miles,img:'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80'});localStorage.setItem('autozone_custom',JSON.stringify(custom));e.target.reset();toast('Vehicle added');render()})}
document.addEventListener('DOMContentLoaded',()=>{initNav();initInventory();initDetails();initForms();initAdmin();const h=$('#homeVehicles');if(h)h.innerHTML=vehicles.slice(0,4).map(card).join('')});
